Add onComplete callback
asbjornh/tiny-spring pull request #1
Opened 2020-08-25 17:52 UTC by mickaelchanrion

Hey!
I'm working on a project using tiny-spring and I need to know when a spring animation is completed so I can do things. Would be nice to have that feature. Tell me if I missed something :)

2020-08-25 19:44 UTC, asbjornh commented
Hi! Thanks for the PR! I’m happy to merge this except for one small thing. The name `onComplete` is kind of misleading since a dynamic spring never really “completes”.

I prefer `onRest` as used by for example react-motion. Maybe also update the docs to reflect that (see for instance [this](https://github.com/chenglou/react-motion#--onrest---void)).

If you make those changes I’ll merge and publish a new version tomorrow! :)

2020-08-25 19:49 UTC, asbjornh requested changes

2020-08-25 19:49 UTC, asbjornh commented on spring.ts
> +      fn(position);
Hmm also I’m not sure that this callback should be called immediately after subscription? I would find that a bit confusing but maybe I’m missing something?

2020-08-26 08:11 UTC, mickaelchanrion commented
Ok. Good catches! I'm fixing all of that

2020-08-26 09:59 UTC, asbjornh approved these changes

2020-08-26 10:00 UTC, merged

2020-08-26 10:00 UTC, asbjornh commented
Cool! Thanks :) I'll publish a new version soon